### ISSUE TITLE
No Lato Font in Header with Light Theme

### ISSUE THREAD

**Issue by DansLeRuSH** [paulmassen/grav-theme-chalk#14]
Hi Paul,

And first of all, thank you for your theme.

I have a small issue : when I apply light theme, it seems that I can't have the Lato font for the header. 

No problem with dark theme 🤔 

Best regards,
Franck

**Comment by paulmassen** [comment]
Hi ! 

Sorry for the late reply. I'm updating the theme just now...

I can't replicate the problem ! I will close this for the moment.

**Comment by paulmassen** [comment]
Years later...but I was able to replicate the problem. Will be fixed in next release. Thanks !
