### ISSUE TITLE
Serve plugins/css/fonts locally

### ISSUE THREAD

**Issue by Finn10111** [paulmassen/grav-theme-chalk#20]
Thanks for this great theme!

But I realized that some content is served not locally but by Google or Cloudflare:

```
cdnjs.cloudflare.com
fonts.googleapis.com
fonts.gstatic.com
```

Is this really necessary for some reason or could it also be served locally and included into the theme? I am really new into Grav and didn't get deep into template development yet but I think it should be possible. 

Just some thoughts by a simple German developer who is concerned about data privacy...

**Comment by Finn10111** [comment]
I tried it by myself and it should be working. If someone would be interested I have created a pull request: https://github.com/paulmassen/grav-theme-chalk/pull/21

Perhaps someone wants to keep the CDNs because of caching, in that case the user should be able to chose between these options in the configuration but at the moment I don't know how to do that.

**Comment by diomed** [comment]
thanks. merged.
