### ISSUE TITLE
Add other Social Links

### ISSUE THREAD

**Issue by cb3inco** [paulmassen/grav-theme-chalk#25]
Is it possible to add other social links like Bitcoin Lightning wallet, Nostr, etc.?

**Comment by paulmassen** [comment]
Hi, the theme use svg icons. It is possible to add your svg icons if you add these to /user/themes/chalk/templates/icons/

Feel free to commit the icons and I will edit the blueprint accordingly so one could edit it from admin.

**Comment by paulmassen** [comment]
Several icons will be added to the theme on the upcoming release this week.

**Comment by paulmassen** [comment]
added in v0.5.0
